"""Add reset password field to user table

Revision ID: 4a3fe41944bf
Revises: 8f2ce8739263
Create Date: 2018-04-09 19:05:55.768000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3fe41944bf'
down_revision = '8f2ce8739263'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_reset_password'), 'users', ['reset_password'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password'), table_name='users')
    op.drop_column('users', 'reset_password')
    # ### end Alembic commands ###
