"""added votes table

Revision ID: 7d87ed1b0f63
Revises: bca0af84279b
Create Date: 2019-07-28 20:45:05.868953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d87ed1b0f63'
down_revision = 'bca0af84279b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('idx_post_kind', 'votes', ['post_id', 'kind'], unique=False)
    op.create_index('idx_user_kind', 'votes', ['user_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_kind', table_name='votes')
    op.drop_index('idx_post_kind', table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
